# -*- coding: utf-8 -*-
"""eeg_visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCfwVaT2vIgpdxL7jHjrdWJW4P-maWZB
"""

!pip install mne

import os
import numpy as np
import mne
import matplotlib.pyplot as plt

# Folder containing the GDF files
folder_path = '/content/drive/MyDrive/SSVEP-based-EEG-signal-processing-main/SSVEP-based-EEG-signal-processing-main/Data'

# List all GDF files in the folder
gdf_files = [f for f in os.listdir(folder_path) if f.endswith('.gdf')]

# Initialize variables for storing data
all_psd = []
all_freqs = None
all_data = []
sfreq = None

for file_name in gdf_files:
    file_path = os.path.join(folder_path, file_name)
    print(f"Loading {file_name}")

    # Load the GDF file
    raw = mne.io.read_raw_gdf(file_path, preload=True)

    # Store sampling frequency (assuming all files have the same sfreq)
    if sfreq is None:
        sfreq = int(raw.info['sfreq'])

    # Compute PSD using `compute_psd()` in newer mne versions
    psd = raw.compute_psd(fmin=1, fmax=30, n_fft=2048)
    psd_data, freqs = psd.get_data(return_freqs=True)
    all_psd.append(psd_data.mean(axis=0))  # Mean across channels

    # Save frequencies (should be same across files)
    if all_freqs is None:
        all_freqs = freqs

    # Append time-series data
    all_data.append(raw.get_data())

# Average PSD across files
average_psd = np.mean(all_psd, axis=0)

# Plot Average PSD
plt.figure(figsize=(10, 6))
plt.plot(all_freqs, average_psd, label='Average PSD across all files')
plt.xlabel('Frequency (Hz)')
plt.ylabel('Power Spectral Density (dB/Hz)')
plt.title('Average Power Spectral Density (1-30 Hz)')
plt.legend()
plt.show()

# Time Series Overlay
average_data = np.mean(np.concatenate(all_data, axis=1), axis=0)

# Plot the averaged time-series data
plt.figure(figsize=(14, 6))
plt.plot(np.linspace(0, len(average_data) / sfreq, len(average_data)), average_data, label='Average Signal')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.title('Average EEG Signal Across All Files')
plt.legend()
plt.show()

